
create table STOCK_MASTER (
	STOCK_KEY	VARCHAR(10) NOT NULL PRIMARY KEY ,
	MARKET_CODE	VARCHAR(5),
	STOCK_CODE	VARCHAR(10) NOT NULL,
	STOCK_NAME	VARCHAR(50)
);

create table STOCK_QUOTE (
	STOCK_KEY	VARCHAR(10) NOT NULL PRIMARY KEY ,
	OPEN	DECIMAL(6,2),
	LAST	DECIMAL(6,2),
	CLOSE	DECIMAL(6,2),
	P_CLOSE	DECIMAL(6,2),
	UPDATED_TIME DATETIME 
);
